### ISSUE TITLE
should not default to now for session start time

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/allen-to-nwb#3]
https://github.com/catalystneuro/allen-to-nwb/blob/c4faa9ce58a3fe6723d74418ab1b6e34335e9037/allen_oephys_to_nwb/allen_oephys_to_nwb.py#L33

**Comment by luiztauffer** [comment]
the original start time is not available. What do you suggest?
@bendichter

**Comment by bendichter** [comment]
I don't know, it's really a shame that this can't be missing. I'd rather put an unreasonable timestamps so it is clear that it is wrong. Maybe 1-1-1900
